name: Lint Frontend

on
  pull_request:
    branches:
      - main

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Check out code
        uses: actions/checkout@v3

      # Schritt 2: Node.js installieren
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Nutze die Version, die dein Projekt benötigt

      # Schritt 3: Abhängigkeiten im Frontend-Ordner installieren
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      # Schritt 4: Lint im Frontend-Ordner ausführen
      - name: Run ESLint
        working-directory: ./Frontend
        run: npm run lint
